### ISSUE TITLE
Can't use NVS in VS-Code?

### ISSUE THREAD

**Issue by vibosxD** [jasongin/nvs#173]
When I run `nvs` in vs-code's power shell I get:
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '"c:/Users/USER/AppData/Roaming/Code'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:811:12)
    at preloadModules (internal/bootstrap/node.js:594:7)
    at startup (internal/bootstrap/node.js:275:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

Works fine when I run it on a standalone shell.

**Comment by jasongin** [comment]
Where do you have `nvs` installed, and how did you install it?
```PowerShell
Get-Command nvs
$env:NVS_HOME
```
Also are you running VS Code Insiders? If so, there might be a problem somewhere handling spaces in the path, since Insiders uses `AppData/Roaming/Code - Insiders`, while that error message cuts off at the first space. However I'd think that could only be an issue if you had installed `nvs` under that path somehow, which would be unusual.

I use `nvs` all the time inside PowerShell in VS Code all the time, so generally it should work. I'm sure we can figure out what the problem is here with some investigation.
