### ISSUE TITLE
EPERM: operation not permitted, lstat 'C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration' Try running again as Administrator.

### ISSUE THREAD

**Issue by Maxim-Mazurok** [jasongin/nvs#217]
It was working fine until recently.
When I try to run `nvs ls` or `nvs menu`, it throws this error:
> EPERM: operation not permitted, lstat 'C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration'
Try running again as Administrator.

My env:
```
C:\Users\maxim>echo %PATH%
C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\7\;C:\Users\maxim\scoop\shims;C:\Users\maxim\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\maxim\AppData\Local\Programs\Python\Python38\;C:\Users\maxim\.windows-build-tools\python27\;C:\Users\maxim\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\maxim\AppData\Local\Programs\Python\Python38-32\;C:\Users\maxim\AppData\Local\Microsoft\WindowsApps;C:\Users\maxim\.dotnet\tools;C:\Users\maxim\AppData\Local\GitHubDesktop\bin;C:\Program Files\nodejs;C:\Users\maxim\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap;C:\Users\maxim\.dotnet\tools;C:\Users\maxim\.deno\bin;C:\Users\maxim\.dotnet\tools;C:\Users\maxim\.dotnet\tools;C:\Users\maxim\AppData\Local\nvs\;C:\Users\maxim\AppData\Local\nvs\default;C:\Users\maxim\.dotnet\tools
```

```
C:\Users\maxim>nvs --version
1.5.2
```

```
OS Name:	Microsoft Windows 10 Pro N
Version:	10.0.19043 Build 19043
```

I don't recall changing any defender rules. One suspicion: windows update fails for me for a while now, maybe during the last "try and revert" cycle it affected something somehow... Will be happy to provide additional info.

**Comment by Maxim-Mazurok** [comment]
I have uninstalled old nvs with choco, installed new 1.6.0, it hangs on "Publishing product information" for hours and doesn't let me cancel the installation.

When I tried to use nvs, it said:

**Comment by Maxim-Mazurok** [comment]
Related to #209 I guess

**Comment by jasongin** [comment]
I don't understand why it would be trying to access that directory. To help diagnose, can you set the `NVS_DEBUG` environment variable?
```cmd
set NVS_DEBUG=1
```

Then run `nvs` again, and it should print a stack trace along with the error. Hopefully that will give us a better clue about what is causing the problem.

**Comment by Maxim-Mazurok** [comment]
Sure, here you go:
```
C:\Users\maxim>set NVS_DEBUG=1

C:\Users\maxim>nvs
Error: EPERM: operation not permitted, lstat 'C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration'
    at Object.lstatSync (fs.js:838:3)
    at childNames.forEach.childName (C:\Users\maxim\AppData\Local\nvs\lib\list.js:175:19)
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\Users\maxim\AppData\Local\nvs\lib\list.js:173:14)
    at childNames.forEach.childName (C:\Users\maxim\AppData\Local\nvs\lib\list.js:166:28)
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\Users\maxim\AppData\Local\nvs\lib\list.js:162:14)
    at childNames.forEach.childName (C:\Users\maxim\AppData\Local\nvs\lib\list.js:156:28)
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\Users\maxim\AppData\Local\nvs\lib\list.js:152:14)
Try running again as Administrator.
```

**Comment by Maxim-Mazurok** [comment]
Also, installing 1.6.0 for all users worked without hanging/freezing.

**Comment by Maxim-Mazurok** [comment]
This is from 1.6.0 all users install:
```
C:\Users\maxim>set NVS_DEBUG=1

C:\Users\maxim>nvs
Error: EPERM: operation not permitted, lstat 'C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration'
    at Object.lstatSync (fs.js:1000:3)
    at C:\ProgramData\nvs\lib\list.js:210:19
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\ProgramData\nvs\lib\list.js:208:14)
    at C:\ProgramData\nvs\lib\list.js:201:28
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\ProgramData\nvs\lib\list.js:197:14)
    at C:\ProgramData\nvs\lib\list.js:191:28
    at Array.forEach (<anonymous>)
    at getVersionsInternal (C:\ProgramData\nvs\lib\list.js:187:14)
Try running again as Administrator.
```

**Comment by jasongin** [comment]
What are the values of the `NVS_ROOT` and `NVS_HOME` env variables, if any?

I suspect some change/misconfiguration of one of those variables might be causing this problem. It should be possible to improve the code to detect that and report a better error message, instead of scan the wrong directories.

**Comment by Maxim-Mazurok** [comment]
```
C:\Users\maxim>echo %NVS_ROOT%
%NVS_ROOT%

C:\Users\maxim>echo %NVS_HOME%
C:\Program Files
```

**Comment by Maxim-Mazurok** [comment]
I've deleted NVS_HOME env var. Installed 1.6.0 for local user - worked fine.
And it now works fine: listed node versions and installed one.
```
C:\Users\maxim>echo %NVS_HOME%
C:\Users\maxim\AppData\Local\nvs\
```

Thanks for the help, not sure why NVS_HOME was invalid. I don't recall changing it manually.
