### ISSUE TITLE
NVS v1.6.2 cannot access remote via https

### ISSUE THREAD

**Issue by finalwhy** [jasongin/nvs#239]
OS：macOS 12.3.1 x64
NVS Version: 1.6.2
Description:

I update NVS to 1.6.2, then i run `nvs add dubnium` and 'nvs ls-remote', it console `Protocol "https:" not supported. Expected "http:"`. I replace the nvs bootstrap node from v16 to v12 (and edit `.nvs/default.json`) and run 'nvs ls-remote' again，then it works. 
I think it might be because of a breaking change in `fs.readDir` between 16 and 12.

ScreenShot:
<img width="926" alt="screenShot" src="https://user-images.githubusercontent.com/24859256/164878016-fd3ecb88-7d24-4456-82e6-e23147ab033c.png">

**Comment by FFengIll** [comment]
meet the same problem

**Comment by jasongin** [comment]
Thanks for reporting. I can't reproduce this error on Mac or Windows, and it wasn't detected in CI tests.

Can you set the environment variable `NVS_DEBUG=1` and run again? That should print a stack trace with the error.

**Comment by jasongin** [comment]
Also, do you have any proxy configured via `HTTP_PROXY` or `HTTPS_PROXY` environment variables?

**Comment by ignorant** [comment]
Same problem occurred.
I am using a proxy.

Upgraded agent-base from 6.0.0 to 6.02 to fix the problem

**Comment by dbalakirev** [comment]
We also resorted to simply use the 1.6.2 version (based on an earlier version of node).

**Comment by gilvandovieira** [comment]
Windows 10
NVS 1.6.2
Node v18.0.0
npm 8.6.0


TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (C:\Users\user\AppData\Local\nvs\deps\node_modules\follow-redirects\index.js:241:24)
    at new RedirectableRequest (C:\Users\user\AppData\Local\nvs\deps\node_modules\follow-redirects\index.js:60:8)
    at Object.wrappedProtocol.request (C:\Users\user\AppData\Local\nvs\deps\node_modules\follow-redirects\index.js:431:14)
    at Object.wrappedProtocol.get (C:\Users\user\AppData\Local\nvs\deps\node_modules\follow-redirects\index.js:436:37)
    at C:\Users\user\AppData\Local\nvs\lib\list.js:351:3
    at new Promise (<anonymous>)
    at getNodejsRemoteVersionsAsync (C:\Users\user\AppData\Local\nvs\lib\list.js:350:9)
